# Generated by Django 2.2.2 on 2019-07-27 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='discription',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='upload',
            name='title',
            field=models.CharField(default='', max_length=500),
        ),
    ]
